# action.yml
name: 'Pandemics actions'
description: 'Publishes a document with Pandemics'
inputs:
  source:
    description: 'Path to the source document(s)'
    required: false
outputs:
  pandemics-dir:
    description: 'Path to pandemics folder'
runs:
  using: 'docker'
  image: 'docker://registry.gitlab.com/pandemics/docker'
  entrypoint: "/bin/sh"
  args:
    - '-c'
    - '/usr/bin/pandemics publish "${INPUT_SOURCE}"; echo "::set-output name=pandemics-dir::$(dirname \"${INPUT_SOURCE}\")/pandemics"'
