# action.yml
name: 'Pandemics actions'
description: 'Publishes a document with Pandemics'
inputs:
  source:
    description: 'Path to the source document'
    required: false
  artifact-name:
    description: 'Name of the uploaded artifact'
    required: false
    default: pandemics

runs:
  using: 'composite'
  steps:
    - name: Publish
      uses: 'docker://registry.gitlab.com/pandemics/docker'
      with:
        entrypoint: "/bin/sh"
        args: '-c "/usr/bin/pandemics publish ${INPUT_SOURCE}"'
    - name: Set output
      id: set-pandemics-dir
      shell: sh
      run: |
        DIR="$(dirname "${INPUT_SOURCE}")/pandemics"
        echo "::set-output name=pandemics-dir::${DIR}"
    - uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.artifact-name }}
        path: ${{ steps.set-pandemics-dir.outputs.pandemics-dir }}
