# action.yml
name: 'Pandemics actions'
description: 'Publishes a document with Pandemics'
inputs:
  source:
    description: 'Path to the source document'
    required: true
  artifact-name:
    description: 'Name of the uploaded artifact'
    required: false
    default: pandemics

runs:
  using: 'composite'
  steps:
    - name: Log
      shell: bash
      run: echo "Publishing ${{ inputs.source }}..."
    - name: Publish
      uses: 'docker://registry.gitlab.com/pandemics/docker'
      with:
        args: "publish ${{ inputs.source }}"
    - name: Set output
      id: set-pandemics-dir
      shell: sh
      run: |
        DIR="$(dirname "${{ inputs.source }}")/pandemics"
        echo "::set-output name=pandemics-dir::${DIR}"
    - name: Check
      shell: bash
      run: "ls ${{ steps.set-pandemics-dir.outputs.pandemics-dir }}"
    - uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.artifact-name }}
        path: ${{ steps.set-pandemics-dir.outputs.pandemics-dir }}
