# action.yml
name: 'Pandemics actions'
description: 'Publishes a document with Pandemics'
author: 'Lionel Rigoux'
inputs:
  source:
    description: 'Path to the source document to compile'
    required: true
outputs:
  artifact-path:
    description: "Path to the folder containing the Pandemics output"
    value: ${{ steps.prepare-output.outputs.pandemics-dir }}

runs:
  using: 'composite'
  steps:
    - name: Prepare output
      id: prepare-output
      shell: bash
      run: |
        DIR="$(dirname ${{ inputs.source }})/pandemics"
        rm -rf ${DIR} 2> /dev/null || true
        echo "Artifact path set to ${DIR}"
        echo "pandemics-dir="${DIR}"" >> $GITHUB_OUTPUT
    - name: Publish
      uses: 'docker://registry.gitlab.com/pandemics/docker'
      with:
        args: "publish ${{ inputs.source }}"
    - name: Check
      shell: bash
      run: "ls ${{ steps.prepare-output.outputs.pandemics-dir }}"

