on:
  push:
    branches:
      - main
  pull_request:

jobs:
  publish-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish
        uses: ./
        with:
          artifact-name: publish-check
