on:
  push:
    branches:
      - master
  pull_request:

jobs:
  publish-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Publish
        id: publish
        uses: ./
        with:
          source: ./README.md
      - uses: actions/upload-artifact@v3
        with:
          name: pandemics
          path: ${{ steps.publish.outputs.artifact-path }}
          if-no-files-found: error
