on:
  push:
    branches:
      - main
  pull_request:

jobs:
  publish-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish
        id: pandemics-publish
        uses: ./
        with:
          source: README.md
      - name: Check target
        run: ls ${{ steps.pandemics-publish.outputs.pandemics-dir }}
