on:
  push:
    branches:
      - master
  pull_request:

jobs:
  publish-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish
        uses: ./
        with:
          source: ./README.md
          artifact-name: publish-check
